-- 코드를 입력하세요
SELECT 
    AO.ANIMAL_ID, 
    AO.NAME
FROM ANIMAL_OUTS AO
JOIN ANIMAL_INS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(SECOND, AI.DATETIME, AO.DATETIME) DESC
LIMIT 2;



# 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회