-- 코드를 작성해주세요
SELECT
  ROUTE,
  CONCAT(TRIM(TRAILING '.0' FROM FORMAT(SUM(D_BETWEEN_DIST), 1)), 'km') AS TOTAL_DISTANCE,
  CONCAT(TRIM(TRAILING '0' FROM TRIM(TRAILING '.' FROM FORMAT(AVG(D_BETWEEN_DIST), 2))), 'km') AS AVERAGE_DISTANCE
FROM
  SUBWAY_DISTANCE
GROUP BY
  ROUTE
ORDER BY
  SUM(D_BETWEEN_DIST) DESC;





