-- 코드를 작성해주세요
SELECT
  SUM(HG.SCORE) AS SCORE,
  HE.EMP_NO,
  HE.EMP_NAME,
  HE.POSITION,
  HE.EMAIL
FROM
  HR_GRADE HG
  JOIN HR_EMPLOYEES HE ON HG.EMP_NO = HE.EMP_NO
WHERE
  HG.YEAR = 2022
GROUP BY
  HG.EMP_NO, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
HAVING
  SUM(HG.SCORE) = (
    SELECT MAX(TOTAL_SCORE) 
    FROM (
      SELECT SUM(SCORE) AS TOTAL_SCORE
      FROM HR_GRADE
      WHERE YEAR = 2022
      GROUP BY EMP_NO
    ) AS T
  )
ORDER BY HE.EMP_NO;
